HTTP 204 response fix and query support on list
mirovit/ionic-platform-sdk pull request #1
Opened 2017-09-10 09:09 UTC by ugurerkan

Hello 😊 

I was using SDK and noticed some problems.
Ionic updated delete request response and SDK throw exception for no content to body.
Also, they added to query options list request for paging and filtering and update SDK for support this too.

Thank you for this amazing work, was saved a lot of time on my schedule.
🍻

2017-09-10 09:11 UTC, ugurerkan commented
I'will fix tests and update soon. 😞

2017-09-10 10:11 UTC, ugurerkan commented
Updated tests @mirovit but **php 5.5 and hhvm fails**. 
Can you help for figure out? I think it's maybe about array bracket syntax on php7 that we use but not sure.

2017-09-10 19:29 UTC, mirovit commented
I guess that it is running a phpunit that is not the local one that I require with the composer.json, try to update the .travis.yml file like this:

```
script:
  - ./vendor/bin/phpunit
```

This should run the local version and not the one from the virtual env of Travis, I guess it is a problem from phpunit.

2017-09-10 21:17 UTC, ugurerkan commented
Thank you 🍻 , updated like you said. 😊 
Now we have problem on nightly build with phpunit 🤔 
https://travis-ci.org/mirovit/ionic-platform-sdk/jobs/273952387

2017-09-11 12:19 UTC, mirovit commented
Okay, just remove the nightly build, I do not think it is very important for now.

2017-09-11 12:21 UTC, mirovit requested changes

2017-09-11 12:21 UTC, mirovit commented on src/Endpoints/Traits/ListsResource.php
> +    public function all(array $query=array())
I prefer using the short array syntax and also it is good to leave space between the = sign - `$query = []`

2017-09-11 12:21 UTC, mirovit commented on src/Endpoints/Traits/ListsResource.php
> +        $response = $this->client->get($this->getEndpoint(),[
Also one space after the comma `$this->getEndpoint(), [`

2017-09-11 12:22 UTC, mirovit requested changes

2017-09-11 12:22 UTC, mirovit commented on tests/Endpoints/Traits/ListsResource.php
> +        $query = array('query' => array());
Also here the short array syntax.

2017-09-11 12:22 UTC, mirovit commented on tests/Endpoints/Traits/ListsResource.php
> +            ->get("{$this->endpoint}{$this->resource}",$query)
An one space after the comma - `"{$this->endpoint}{$this->resource}", $query`

2017-09-11 18:51 UTC, ugurerkan reviewed
Thank you for your review and help @mirovit 
Updated PR with changes, everything seems well now.

2017-09-11 18:57 UTC, mirovit approved these changes

2017-09-11 18:57 UTC, merged

2017-09-11 18:59 UTC, mirovit commented
Thanks for the contribution and I hope this package is of use to you :)

2017-09-11 19:06 UTC, ugurerkan commented
Of course it is, very well designed and practical, thank you. 😍